### ISSUE TITLE
Silent errors?

### ISSUE THREAD

**Issue by maximilianschmitt** [everysquare/pollinate#11]
Hi! I would love to use pollinate. However, if I run `pollinate wunderflats/javascript-boilerplate '{"packageName": "hello"}'`, it does nothing.

```
~/javascript-boilerplate $ pollinate wunderflats/javascript-boilerplate '{"packageName": "hello"}'
~/javascript-boilerplate $ ls
~/javascript-boilerplate $
```

```
$ node -v
v5.3.0
$ npm -v
3.5.2
```

**Comment by howardroark** [comment]
Ah! I will have to look into this for sure.  I actually have not tested it on node version 5 yet.

**Comment by howardroark** [comment]
@maximilianschmitt Yo definitely identified some bugs! I just fixed them an released a new version.  This project is still in a beta state, as it has just been me trying it out up until now.

I took a look at your repo, and there are few things that do need updating.The project requires a file called `flower.json` to exist in the repo.  This is a sort of the "default object".  Also any "contextual" data needs to be supplied as the object property `context`.  One exception is `name` , which looks to be what you may want to use in your example.

I have a sent you a pull request.  If you update pollinate this should work using that PR...

```
pollinate wunderflats/javascript-boilerplate '{"name":"test"}'
```

You are raising some good scenarios!  I was thinking of making it so `package.json` could also act as `flower.json`, made an issue for it, but still not sure if it is the right move (since you can just discard it).

**Comment by maximilianschmitt** [comment]
@howardroark great, thank you very much, seems to be working now! :)
